version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: auth
    restart: always
    environment:
      POSTGRES_USER: auth-postgres
      POSTGRES_PASSWORD: auth-postgres-123
      POSTGRES_DB: authDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: